# Generated by Django 6.0.6 on 2026-06-11 05:36

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessElement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "business element",
                "verbose_name_plural": "business elements",
                "db_table": "access_business_element",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "role",
                "verbose_name_plural": "roles",
                "db_table": "access_role",
            },
        ),
        migrations.CreateModel(
            name="AccessRule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("can_read", models.BooleanField(default=False)),
                ("can_read_all", models.BooleanField(default=False)),
                ("can_create", models.BooleanField(default=False)),
                ("can_update", models.BooleanField(default=False)),
                ("can_update_all", models.BooleanField(default=False)),
                ("can_delete", models.BooleanField(default=False)),
                ("can_delete_all", models.BooleanField(default=False)),
                (
                    "element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_rules",
                        to="access_control.businesselement",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_rules",
                        to="access_control.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "access rule",
                "verbose_name_plural": "access rules",
                "db_table": "access_rule",
                "constraints": [
                    models.UniqueConstraint(fields=("role", "element"), name="uq_access_rule")
                ],
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to="access_control.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to="authentication.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "user role",
                "verbose_name_plural": "user roles",
                "db_table": "access_user_role",
                "constraints": [
                    models.UniqueConstraint(fields=("user", "role"), name="uq_user_role")
                ],
            },
        ),
    ]
